version: '3.8'

services:
  server:
    build: ./master/
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - REPLICA_HOST_1=http://replica_1:5001
      - REPLICA_HOST_2=http://replica_2:5001
      - REPLICA_HOST_3=http://replica_3:5001
      - CONCERN=3
    volumes:
      - ./master:/app

  replica_1:
    build: ./replica/
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - SLEEP=30
    volumes:
      - ./replica:/app

  replica_2:
    build: ./replica/
    ports:
      - "5002:5001"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - SLEEP=10
    volumes:
      - ./replica:/app

  replica_3:
    build: ./replica/
    ports:
      - "5003:5001"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - SLEEP=20
    volumes:
      - ./replica:/app