version: '3.8'

services:
  server:
    build: ./master/
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - REPLICA_HOST_1=http://replica_1:5000
      - REPLICA_HOST_2=http://replica_2:5000
      - REPLICA_HOST_3=http://replica_3:5000
      - CONCERN=3
    volumes:
      - ./master:/app

  replica_1:
    build: ./master/
    ports:
      - "5001:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - SLEEP=30
      - APP_MODE=replica
    volumes:
      - ./master:/app

  replica_2:
    build: ./master/
    ports:
      - "5002:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - SLEEP=10
      - APP_MODE=replica
    volumes:
      - ./master:/app

  replica_3:
    build: ./master/
    ports:
      - "5003:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - SLEEP=20
      - APP_MODE=replica
    volumes:
      - ./master:/app